name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: P1
      id: p1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: P1
        setup-command: ''
        command: python3 Examen2.py
        input: '1'
        expected-output: "['HTML', 'CSS', 'JS', 'React', 'Redux', 'Node', 'Express',
          'MongoDB']"
        comparison-method: contains
        timeout: 1
        max-score: 25
    - name: P2
      id: p2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: P2
        setup-command: ''
        command: python3 Examen2.py
        input: '2'
        expected-output: "{19, 20, 22, 24, 25, 26, 27, 28}"
        comparison-method: contains
        timeout: 10
    - name: P3
      id: p3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: P3
        setup-command: ''
        command: python3 Examen2.py
        input: '3'
        expected-output: |-
          0
          1
          1
          4
          4
          9
          9
          16
          16
          25
          25
          36
          36
          49
          49
          64
          64
          81
          81
          100
          100
          121
          121
          144
          144
          169
          169
          196
          196
          225
          225
          256
          256
          289
          289
          324
          324
          361
          361
          400
          400
          441
          441
          484
          484
          529
          529
          576
          576
          625
          625
          676
          676
          729
          729
          784
          784
          841
          841
          900
          900
          961
          961
          1024
          1024
          1089
          1089
          1156
          1156
          1225
          1225
          1296
          1296
          1369
          1369
          1444
          1444
          1521
          1521
          1600
          1600
          1681
          1681
          1764
          1764
          1849
          1849
          1936
          1936
          2025
          2025
          2116
          2209
          2209
          2304
          2304
          2401
          2401
          2500
          2500
        comparison-method: contains
        timeout: 1
        max-score: 25
    - name: P4
      id: p4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: P4
        setup-command: ''
        command: python3 Examen2.py
        input: '4'
        expected-output: '77.0'
        comparison-method: contains
        timeout: 1
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        P1_RESULTS: "${{steps.p1.outputs.result}}"
        P2_RESULTS: "${{steps.p2.outputs.result}}"
        P3_RESULTS: "${{steps.p3.outputs.result}}"
        P4_RESULTS: "${{steps.p4.outputs.result}}"
      with:
        runners: p1,p2,p3,p4
